// TODO CHANGE NAMES TO ICECREAM__[ACTION NAME]
// ICECREAMS
export const ICECREAM_INIT = 'ICECREAM_INIT';
export const ICECREAM_ADD = 'ICECREAM_ADD';
export const ICECREAM_REMOVE = 'ICECREAM_REMOVE';
export const ICECREAM_SET = 'ICECREAM_SET';
export const ICECREAM_FETCH_FAIL = 'ICECREAM_FETCH_FAIL';

export const SUMMARY_OPEN = 'SUMMARY_OPEN';

// ORDERS - POST
export const ORDER_POST = 'ORDER_POST';
export const ORDER_POST_START = 'ORDER_POST_START';
export const ORDER_POST_SUCCESS = 'ORDER_POST_SUCCESS';
export const ORDER_POST_FAIL = 'ORDER_POST_FAIL';
// ORDERS - GET
export const ORDER_GET = 'ORDER_GET';
export const ORDER_GET_START = 'ORDER_GET_START';
export const ORDER_GET_SUCCESS = 'ORDER_GET_SUCCESS';
export const ORDER_GET_FAIL = 'ORDER_GET_FAIL';


// AUTH
export const AUTH = 'AUTH';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_CHECK_ON_START = 'AUTH_CHECK_ON_START';
