// TODO CHANGE NAMES TO ICECREAM__[ACTION NAME]
// ICECREAMS
export const ICECREAM_INIT = 'ICECREAM_INIT';
export const ADD_ICECREAM = 'ADD_ICECREAM';
export const REMOVE_ICECREAM = 'REMOVE_ICECREAM';
export const SET_ICECREAM = 'SET_ICECREAM';
export const FETCH_FAIL_ICECREAM = 'FETCH_FAIL_ICECREAM';
export const OPEN_SUMMARY = 'OPEN_SUMMARY';

// ORDERS

// AUTH
export const AUTH = 'AUTH';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_CHECK_ON_START = 'AUTH_CHECK_ON_START';
